# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: DockerCI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.github/ISSUE_TEMPLATE/**'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Set up build environment
      - uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675
        with:
          fetch-depth: 0
      - name: Set up JDK 8
        uses: actions/setup-java@d202f5dbf7256730fb690ec59f6381650114feb2
        with:
          java-version: 8
      - uses: actions/cache@d1255ad9362389eac595a9ae406b8e8cb3331f16 # save wrapper
        with:
          path: |
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-wrapper-
      - name: Docker Login
        uses: docker/login-action@f3364599c6aa293cdc2b8391b1b56d0c30e45c8a
        with:
          registry: nagyesta-docker-releases.bintray.io
          username: ${{ secrets.BINTRAY_USER }}
          password: ${{ secrets.BINTRAY_TOKEN }}
      - name: Publish Docker image with Gradle
        run: ./gradlew tagVersion publish -PgithubToken=${{ secrets.PUBLISH_KEY }}
